node {
  stage('SCM') {
    git 'https://git@github.com:nickgulrajani/sonar-scanning-examples.git'
  }
  stage('SonarQube' ) {
    def scannerHome = tool 'SonarQube';
      sh "${scannerHome}/bin/sonar-scanner"
    }
  }
}
